=== Siuuuers/dwm/data/schemas/desktop-issuer-root.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "desktop-issuer-root",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"schema_version",
		"namespace",
		"next_counter",
		"receipts",
		"allocation_receipts",
		"day_advance_allocation_receipts"
	],
	"properties": {
		"schema_version": {"const": 1},
		"namespace": {"type": "string", "minLength": 64},
		"next_counter": {"type": "integer"},
		"receipts": {"type": "object"},
		"allocation_receipts": {"type": "object"},
		"day_advance_allocation_receipts": {"type": "object"}
	}
}

=== Siuuuers/dwm/evidence/phase_2r/current_ci_20261023/run39979681421/12514425452/terminal-root/desktop-issuer-root.json
{"allocation_receipts":{"transaction_id.56c23fd7fc2501caa67eca90d76887259ddf0f9567d964c05a1837c2f5919c7d":{"branch_id":"branch_id.078a77338ca395cae2b0984c1bf0c883514ff4fc1ff37b57957cacf9530f8731","branch_id_issuer_receipt":{"counter":88,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"branch_id","receipt_id":"issuer_receipt.0653f10c9173bc2a8fbeb8e4e5b12c2f059ee630a333b6279a136d2a510c214c","token":"branch_id.078a77338ca395cae2b0984c1bf0c883514ff4fc1ff37b57957cacf9530f8731"},"causal_day_instance":"causal_day_instance.092d1696ab99f3bb9b889ba53b710feddfd5632d09e76419c9e196dbc0fc1d90","causal_day_instance_issuer_receipt":{"counter":90,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"causal_day_instance","receipt_id":"issuer_receipt.732f4a3c4280386e31ef8454f393a3f88b8bad8ba98a8e3ea8522125d8857d19","token":"causal_day_instance.092d1696ab99f3bb9b889ba53b710feddfd5632d09e76419c9e196dbc0fc1d90"},"desktop_timeline_generation":0,"desktop_timeline_generation_issuer_receipt":{"counter":89,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":0,"purpose":"desktop_timeline_generation","receipt_id":"issuer_receipt.76fe196055efad5b023ef93e04715ea3cc17e7df80843153120f27fa8ba84b4f","token":"desktop_timeline_generation.34ab8d9dcfe12656a289844eac5176332c45d94e0212ed2a5446802c2f809f3d"},"kind":"new_run","remap_transaction_issuer_receipts":{},"request":{"existing_run_id":null,"kind":"new_run","remap_source_transaction_ids":[],"source_desktop_timeline_generation":null,"transaction_id":"transaction_id.56c23fd7fc2501caa67eca90d76887259ddf0f9567d964c05a1837c2f5919c7d","transaction_issuer_receipt":{"counter":86,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"transaction_id","receipt_id":"issuer_receipt.b949e226ec0f7d7b3f754ccd7d1f307d3155e33967fe1d00fdb391393a99b163","token":"transaction_id.56c23fd7fc2501caa67eca90d76887259ddf0f9567d964c05a1837c2f5919c7d"}},"root_namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","root_next_counter":87,"run_id":"run_id.0cd6b1a0360d52d853d673afb9f3f7f491b4b765a94e0a40618d81c8c9243d39","run_id_issuer_receipt":{"counter":87,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"run_id","receipt_id":"issuer_receipt.4ab362f323f547d8cb39c80b8e7c07403689941da173fe8ae0edd6a850b4c151","token":"run_id.0cd6b1a0360d52d853d673afb9f3f7f491b4b765a94e0a40618d81c8c9243d39"},"schema_version":1,"transaction_remap":{}},"transaction_id.8414c766acbdc14dbd8272c8d36c63a000e9b431f7a445ca25e48c2ce73c6428":{"branch_id":"branch_id.71e888f13609fbaa4157426408f28b5f50577f7e7298eee28834df427b6a32f0","branch_id_issuer_receipt":{"counter":83,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"branch_id","receipt_id":"issuer_receipt.36ac93bb0beebb3699fcf9763ac7f44f43dadfb90ca46803da9fe555c79bbcaa","token":"branch_id.71e888f13609fbaa4157426408f28b5f50577f7e7298eee28834df427b6a32f0"},"causal_day_instance":"causal_day_instance.12b4145db407ea457434c1cb8714f269b29845ab318e7f52b159891414deaf34","causal_day_instance_issuer_receipt":{"counter":85,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"causal_day_instance","receipt_id":"issuer_receipt.faac1660cf6ec9b59b02b04659daf13f931b9cb8d74544a8c504a4af63436ac2","token":"causal_day_instance.12b4145db407ea457434c1cb8714f269b29845ab318e7f52b159891414deaf34"},"desktop_timeline_generation":3,"desktop_timeline_generation_issuer_receipt":{"counter":84,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":3,"purpose":"desktop_timeline_generation","receipt_id":"issuer_receipt.4babbe5d54bb7f1883c621f35aa98e3769fc7c1064a26d8dc53ddcd198590bf0","token":"desktop_timeline_generation.5541693e1b29a4cd930cbf1f0bb025b6df992b49615c0e8bcd688746ae493776"},"kind":"restore","remap_transaction_issuer_receipts":{},"request":{"existing_run_id":"run_id.ec5ebbe37aaeb707b927fbe22281544e0dfcf8f395b204a0dba301ac0185c34e","kind":"restore","remap_source_transaction_ids":[],"source_desktop_timeline_generation":2,"transaction_id":"transaction_id.8414c766acbdc14dbd8272c8d36c63a000e9b431f7a445ca25e48c2ce73c6428","transaction_issuer_receipt":{"counter":82,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"transaction_id","receipt_id":"issuer_receipt.aa32ef9a09b6fed470835ecca801d121a26641c0dbf2a1c78d98b99c359fc6b1","token":"transaction_id.8414c766acbdc14dbd8272c8d36c63a000e9b431f7a445ca25e48c2ce73c6428"}},"root_namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","root_next_counter":83,"run_id":"run_id.ec5ebbe37aaeb707b927fbe22281544e0dfcf8f395b204a0dba301ac0185c34e","run_id_issuer_receipt":null,"schema_version":1,"transaction_remap":{}},"transaction_id.9d12d6ef8e663400e53015f1b6f23a4385766a320e191ec045f79c2b8ddc5807":{"branch_id":"branch_id.8f1ce18596d57069b6307050009f36881f0d6ca281a4c8e08a57d0dccb78f358","branch_id_issuer_receipt":{"counter":37,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"branch_id","receipt_id":"issuer_receipt.85226747385aa854f88f8955dc434348b5eb568a2afa5f830b588099e699fa93","token":"branch_id.8f1ce18596d57069b6307050009f36881f0d6ca281a4c8e08a57d0dccb78f358"},"causal_day_instance":"causal_day_instance.a5ae9228e7e3f7182927a03f76a15729a64716c52fbd7a5cc8d0a64c3a8e42b3","causal_day_instance_issuer_receipt":{"counter":39,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"causal_day_instance","receipt_id":"issuer_receipt.8cd0e9375f1f77afc54738d44aee1231c79834cc805c780de09f1bd4eac0c58c","token":"causal_day_instance.a5ae9228e7e3f7182927a03f76a15729a64716c52fbd7a5cc8d0a64c3a8e42b3"},"desktop_timeline_generation":1,"desktop_timeline_generation_issuer_receipt":{"counter":38,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":1,"purpose":"desktop_timeline_generation","receipt_id":"issuer_receipt.1b8a49ef5e45d64e20e4f0c536285dcaa8ca5e8367e5528ffeba2747f0ef5593","token":"desktop_timeline_generation.4459d560cbe69314152203c256d8f39bb2c6d11a85f18aacf5f33deeb910612d"},"kind":"restore","remap_transaction_issuer_receipts":{},"request":{"existing_run_id":"run_id.ec5ebbe37aaeb707b927fbe22281544e0dfcf8f395b204a0dba301ac0185c34e","kind":"restore","remap_source_transaction_ids":[],"source_desktop_timeline_generation":0,"transaction_id":"transaction_id.9d12d6ef8e663400e53015f1b6f23a4385766a320e191ec045f79c2b8ddc5807","transaction_issuer_receipt":{"counter":36,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"transaction_id","receipt_id":"issuer_receipt.32cf5fb7926107494885e1c7d9a8a233709adebde556bc2b72c1128fa590af4a","token":"transaction_id.9d12d6ef8e663400e53015f1b6f23a4385766a320e191ec045f79c2b8ddc5807"}},"root_namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","root_next_counter":37,"run_id":"run_id.ec5ebbe37aaeb707b927fbe22281544e0dfcf8f395b204a0dba301ac0185c34e","run_id_issuer_receipt":null,"schema_version":1,"transaction_remap":{}},"transaction_id.c9da9b905e563a35d667aefcd1f0d26a5b8eaa8b49cbb292195d61e3a183862d":{"branch_id":"branch_id.54456c063ae29d4a27bd06b306c360ea258609cfd90f489534ad52a79ddf9013","branch_id_issuer_receipt":{"counter":75,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"branch_id","receipt_id":"issuer_receipt.14c2e820266b0d5ed799573566b9dea39aa8ad0a4a9fdc0c468a8bf048119993","token":"branch_id.54456c063ae29d4a27bd06b306c360ea258609cfd90f489534ad52a79ddf9013"},"causal_day_instance":"causal_day_instance.3b9a493b660efaeec1a1e36cfe96f9f7de0bd12ffa983a557fd5e26bd320c75d","causal_day_instance_issuer_receipt":{"counter":77,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"causal_day_instance","receipt_id":"issuer_receipt.b6090dd030064391d5bad43c0ee8a0cc9e2ca10761b010119a138d8ca8100987","token":"causal_day_instance.3b9a493b660efaeec1a1e36cfe96f9f7de0bd12ffa983a557fd5e26bd320c75d"},"desktop_timeline_generation":2,"desktop_timeline_generation_issuer_receipt":{"counter":76,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":2,"purpose":"desktop_timeline_generation","receipt_id":"issuer_receipt.d527b98a865b85bda7707a274d81db2fa5c11bcc502e69bbc544fb0f50c96e61","token":"desktop_timeline_generation.d29e206e7b607c54812744ab3ebfd3d7b85d77c8229ed7ffab742bed4cb720ea"},"kind":"restore","remap_transaction_issuer_receipts":{},"request":{"existing_run_id":"run_id.ec5ebbe37aaeb707b927fbe22281544e0dfcf8f395b204a0dba301ac0185c34e","kind":"restore","remap_source_transaction_ids":[],"source_desktop_timeline_generation":1,"transaction_id":"transaction_id.c9da9b905e563a35d667aefcd1f0d26a5b8eaa8b49cbb292195d61e3a183862d","transaction_issuer_receipt":{"counter":74,"namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","numeric_value":null,"purpose":"transaction_id","receipt_id":"issuer_receipt.2d95da06df33b4c6f36de0531de2748195a4b35426b812e493adbaccd3c33a10","token":"transaction_id.c9da9b905e563a35d667aefcd1f0d26a5b8eaa8b49cbb292195d61e3a183862d"}},"root_namespace":"db703c51e0167b9ccfe6d9a2371b864555aab83e25e341f20908fee883ec2615","root_next_counter":75,"run_id":"run_id.ec5ebbe37aaeb707b927fbe22281544e0dfcf8f395b204a0dba301ac0185c34e","run_id_issuer_receipt":null,"schema_version":1,"transaction_remap":{}},"transaction_id.ec61a741adff4def08dd265c5ee5a8a8f170fc15db36010630c70b47da8c9437":{"branch_id":"branch_id.6b66f8b1e9158b95fb1e7a1debb78b2700bfa3bd4a5393d578c7e64b15
